---
title: "DEE Well Separated Print Out"
author: "Jonathan Klus"
date: "2024-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# load necessary functions
# source("./Multivariate_DPMM_unknownvar_DEE.R")
# source("./Multivariate_DPMM_nonconj_DEV.R")
# source("./Multivariate_DPMM_nonconj_UVV.R")
# source("./posterior_helper_fxns.R")
# source("./post_processing_inf.R")

# load R libraries
library(ggplot2)
library(mclust)
library(LaplacesDemon)
library(mvtnorm)
library(stringr)
library(gridExtra)
library(dplyr)
library(knitr) # kable
library(kableExtra) # use for complex tables http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
library(xtable)
library(scatterplot3d)
```

# Isolating issues in previously run DEE simulation, seed #1

```{r, echo=TRUE, warning=FALSE, message=FALSE}
data_path = "/projects/jklus/JKSTproj/BlueHive_Sim_Results/SummaryPriorScale"
sim_dir = "MODSUM_conjDEE_3wellsep_n30_noSM_sim_results_2024_10_31"  
output = readRDS(paste0(data_path,"/",sim_dir,"/sum_1.rds"))
highvar_iters = which(output$var_list_by_k_stephens[[1]]$sigma_1_1 > 100)
highvar_iters

# how often are MCMC iterations within a given range?
mean(output$var_list_by_k_stephens[[1]]$sigma_1_1 <20)
mean(output$var_list_by_k_stephens[[1]]$sigma_1_1 <15 & output$var_list_by_k_stephens[[1]]$sigma_1_1 > 5)

plot_iter <- function(output, iter){
  
  # cat("\n Variance terms from iter: \n")
  # print(output$var_list_by_k_stephens[[1]]$sigma_1_1[iter])
  
  yvals = matrix(data = unlist(output$data), ncol = nrow(output$data[[1]]), byrow = TRUE)
  plot_y = data.frame(
    y1 = yvals[,1],
    y2 = yvals[,2],
    curr_assign = output$group_assign[iter,]
  )
  
  prog_plot = ggplot(data = plot_y, aes(x = y1, y = y2, label = plot_y$curr_assign)) +
    geom_text(size = 3, color = plot_y$curr_assign) +
    ggtitle(paste0("Group Assignments:", " iter = ", iter, " , Var = ",
                   round(output$var_list_by_k_stephens[[1]]$sigma_1_1[iter],0), 
                   " ,K = ", length(unique(plot_y$curr_assign)))) +
    theme_classic()
  
  return(prog_plot)
  
}

```
```{r, echo=TRUE}
cat("\n Variances for surrounding iterations: \n")
output$var_list_by_k_stephens[[1]]$sigma_1_1[320:340]
cat("\n")
plot_iter(output = output, iter = 323)
plot_iter(output = output, iter = 324)
plot_iter(output = output, iter = 325)
plot_iter(output = output, iter = 326)
plot_iter(output = output, iter = 327)
```

```{r, echo=TRUE}
cat("\n Variances for surrounding iterations: \n")
output$var_list_by_k_stephens[[1]]$sigma_1_1[540:560]
cat("\n")
plot_iter(output = output, iter = 545)
plot_iter(output = output, iter = 546)
plot_iter(output = output, iter = 547)
```

```{r, echo=TRUE}
cat("\n Variances for surrounding iterations: \n")
output$var_list_by_k_stephens[[1]]$sigma_1_1[4880:4910]
cat("\n")
plot_iter(output = output, iter = 4888)
plot_iter(output = output, iter = 4889)
plot_iter(output = output, iter = 4890)
plot_iter(output = output, iter = 4891)
plot_iter(output = output, iter = 4892)
plot_iter(output = output, iter = 4893)
plot_iter(output = output, iter = 4894)
plot_iter(output = output, iter = 4895)
```

```{r, echo=TRUE}
cat("\n Variances for surrounding iterations: \n")
output$var_list_by_k_stephens[[1]]$sigma_1_1[11150:11170]
cat("\n")
plot_iter(output = output, iter = 11156)
plot_iter(output = output, iter = 11157)
plot_iter(output = output, iter = 11158)
```

```{r, include=FALSE, eval=FALSE}
# Well separated simulation setting 

################## simulate data ##############################################

set.seed(516)
x = 1 # dataset100
seeds = readRDS("./BHsimseeds.rds")


w = c(0.4, 0.3, 0.3)

means = list(
    c(-20, 20),
    c(20, -20),
    c(0, 0)
  )


var = diag(10, length(means[[1]])) # variances known, diagonal, and equal


set.seed(seeds[x])
assign = sample(x = 1:length(means), size = 100, replace = TRUE, prob = w)
y = lapply(X = assign,
          FUN = function(x){
          t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
            })


# drop params used to generate data, except for var which is assumed known
mu_true = means
var_true = var
# yreps # 2nd element is assign
rm(w, means)
```



```{r, include=FALSE, eval=FALSE}
### Fit DEE model
n_iter = 10
# set hyperparameters
# a = 1; b = 50
# d = 1; f = 1
# g = 1; h = 50
# sigma0 = 200
# lambda0 = diag(x = 25, nrow = length(means[[1]])) # needed for UVV
# nu = length(means[[1]])  # must have nu >= p...Otherwise rinvwish will fail!

# run in fxn
sim_results_DEE_with_sm = MVN_CRP_sampler_DEE(
        S = n_iter, seed = seeds[x], y = y,
        alpha = 1, r = 10, d = 1, f = 1 , g = 1, h = 50,
        sigma_hyperprior = FALSE, fix_r = FALSE,
        mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1),
        a = 5, b = 50,
        k_init = 3, init_method = "kmeans", diag_weights = FALSE, 
        verbose = TRUE, split_merge = FALSE, print_iter = 1, print_start = 1000
        )

mod_sum = dpmm_summary(output = sim_results_DEE_with_sm, 
       print_k_sum = TRUE, 
       print_phi_sum = TRUE,
       make_traceplot = FALSE,
       burn_in = 0, t_hold = 100, 
       num_dims = 2, equal_var = TRUE,
       calc_perf = TRUE, mu_true = mu_true, 
       var_true = var_true, assign_true = assign)

plot(mod_sum$var_list_by_k_stephens[[1]]$sigma_1_1, type = "l", 
     xlab = "iter", ylab = "sigma2")
```

