---
title: "Gamma Hyperprior on Variance"
author: "Jonathan Klus"
date: "2023-07-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load necessary functions
source("./Multivariate_DPMM_unknownvar.R")
source("./posterior_helper_fxns.R")

# load R libraries
library(ggplot2)
library(plotly)
library(label.switching)
library(coda)
library(tidyr)
```

## 2D Example - close together

Mixture of 3 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 10$. The true means are $(10,10)$, $(0,-5)$, , $(12,-2)$, and $(0,10)$, and
$\sum_{j}n_j = 50$.

```{r, echo=FALSE}
################## simulate data ##############################################
set.seed(1234)
w = c(.35, .25, .4)
means = list(
  #c(10, 10),
  c(0, -5),
  c(0, 10),
  c(12,2)
)

var = diag(9, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 50, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

# empirical means and variances
data %>%
  group_by(assign) %>%
  dplyr::summarize(mean(y1), mean(y2), var(y1), var(y2))

ggplot(data = data, aes(x = y1, y = y2)) +
  geom_point(color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```

### Using IG(1, b) w/ b~Ga(1,1) and empirical mean/var as prior

```{r,  message=FALSE}
# sample
set.seed(718)
n_iter = 1000
mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -1)
print(mu0)
print(Sigma0)

ex3 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
                        mu0 = mu0, a = 1, d = 1, f = 1, sigma_hyperprior = TRUE, diag_weights = TRUE,
                        k_init = 1, verbose = TRUE, print_iter = 1000)
# saveRDS(object = list(data = data, mcmc = ex3), file = paste0("./MCMC_Runs/MCMC_run_hyperprior_a1_d1_f1_n50_", Sys.Date(),".rds"))
# ex3 = readRDS("./MCMC_Runs/MCMC_run_hyperprior_a1_d1_f1_n50_2023-08-03.rds")$mcmc
mean(ex3$accept[2:n_iter,])
table(ex3$k)

# traceplot for number of components k.

make_k_traceplot(k = ex3$k, group_assign = ex3$group_assign)
  
# ggplot(mapping = aes(x = 1:n_iter, y = ex3$k)) + 
#   geom_line() +
#   ggtitle("Traceplot of no. components K") +
#   xlab("iter") + 
#   ylab("K") + 
#   theme_classic()

# posterior inference before label switching fixed
mean_list_by_k3 = list_params_by_k(draws = ex3$means, burn_in = 1000, param_type = "Mean", k_vec = ex3$k)
var_list_by_k3 = list_params_by_k(draws = ex3$vars, burn_in = 1000, param_type = "Var", k_vec = ex3$k)
#sigma22 is group 2, 2nd diagonal element
prob_list_by_k3 = get_probs_by_k(probs = ex3$group_probs, 
                                n_groups = ex3$k, 
                                burn_in = 1000)
group_assign_list_by_k3 = get_assign_by_k(assign = ex3$group_assign, 
                                         n_groups = ex3$k, 
                                         burn_in = 1000)
## deal with label switching for each k

## in this case need to skip first result bc only one group was found -- can't 
## have label switching when there is only 1 group so the function fails

## this ended up not being true here after some settings were changed --- need to program
## a more robust way to do this to avoid manually changing Stephens settings and potentially
## causing erros
stephens_result3 = get_stephens_result(group_assign_list_by_k = group_assign_list_by_k3, 
                                       prob_list_by_k = prob_list_by_k3)

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$means, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3, 
                                           param_type = "Mean")
var_list_by_k_stephens3 = list_params_by_k(draws = ex3$vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

# posterior means
make_postsum(mcmc_df = mean_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[3]], digits = 2)

# posterior vars
make_postsum(mcmc_df = var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[3]], digits = 2)




# empirical means & vars
# emp_mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_means, k_vec = ex3$k,
#                                            burn_in = 1000,
#                                            relabel = TRUE,
#                                            permutation = stephens_result3, 
#                                            param_type = "Mean")
emp_var_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

# empirical vars
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[3]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 2,
               param_type = "Mean")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 4, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 4, p = 2,
               component_no = 2,
               param_type = "Mean")

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 4, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 4, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 5, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 5, p = 2,
               component_no = 2,
               param_type = "Mean")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 5, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 5, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

## traceplot of b parameters
b_mcmc_draws = data.frame(ex3$b) %>%
  dplyr::mutate(iter = 1:nrow(ex3$b)) %>%
  tidyr::pivot_longer(cols = c("b_1", "b_2"),
                      names_to = "component",
                      values_to = "param")

ggplot(data = b_mcmc_draws) +
  geom_line(mapping = aes(x = iter, y = param, color = component)) +
  ggtitle("Traceplot of b") +
  # ylab() +
  theme_classic()

# explore variance spikes
var_spike = sapply(X = 1:length(ex3$vars), FUN = function(x){max(unlist(ex3$vars[[x]]))})
spike_ind = which(var_spike > 100)
spike_ind = spike_ind[(spike_ind>1000)==TRUE] # neglect burn in iters
spike_info = lapply(X = 1:length(spike_ind), 
       FUN = function(x){
         list(iter = spike_ind[x], tabs = table(ex3$group_assign[spike_ind[x],]))
       })
```

### Using IG(1, b) w/ b~Ga(1,10) and empirical mean/var as prior

```{r,  message=FALSE}
# sample
set.seed(718)
n_iter = 11000
mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -1)
print(mu0)
print(Sigma0)

# ex3 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
#                         mu0 = mu0, a = 1, d = 1, f = 10, sigma_hyperprior = TRUE,
#                         k_init = 1, verbose = TRUE, print_iter = 1000)
# saveRDS(object = list(data = data, mcmc = ex3), file = paste0("./MCMC_Runs/MCMC_run_hyperprior_a1_d1_f10_n50_", Sys.Date(),".rds"))
ex3 = readRDS("./MCMC_Runs/MCMC_run_hyperprior_a1_d1_f10_n50_2023-08-03.rds")$mcmc
mean(ex3$accept[2:n_iter,])
table(ex3$k)

# traceplot for number of components k
make_k_traceplot(k = ex3$k, group_assign = ex3$group_assign, burn_in = 1000)

# posterior inference before label switching fixed
mean_list_by_k3 = list_params_by_k(draws = ex3$means, burn_in = 1000, param_type = "Mean", k_vec = ex3$k)
var_list_by_k3 = list_params_by_k(draws = ex3$vars, burn_in = 1000, param_type = "Var", k_vec = ex3$k)
#sigma22 is group 2, 2nd diagonal element
prob_list_by_k3 = get_probs_by_k(probs = ex3$group_probs, 
                                n_groups = ex3$k, 
                                burn_in = 1000)
group_assign_list_by_k3 = get_assign_by_k(assign = ex3$group_assign, 
                                         n_groups = ex3$k, 
                                         burn_in = 1000)
## deal with label switching for each k

## in this case need to skip first result bc only one group was found -- can't 
## have label switching when there is only 1 group so the function fails

## this ended up not being true here after some settings were changed --- need to program
## a more robust way to do this to avoid manually changing Stephens settings and potentially
## causing erros
stephens_result3 = get_stephens_result(group_assign_list_by_k = group_assign_list_by_k3, 
                                       prob_list_by_k = prob_list_by_k3)

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$means, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3, 
                                           param_type = "Mean")
var_list_by_k_stephens3 = list_params_by_k(draws = ex3$vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

make_postsum(mcmc_df = mean_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[3]], digits = 2)

make_postsum(mcmc_df = var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[3]], digits = 2)

# empirical means & vars
# emp_mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_means, k_vec = ex3$k,
#                                            burn_in = 1000,
#                                            relabel = TRUE,
#                                            permutation = stephens_result3, 
#                                            param_type = "Mean")
emp_var_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

# empirical vars
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[3]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 2,
               param_type = "Mean")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 4, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 4, p = 2,
               component_no = 2,
               param_type = "Mean")

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 4, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 4, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 5, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 5, p = 2,
               component_no = 2,
               param_type = "Mean")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 5, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 5, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

## traceplot of b parameters
b_mcmc_draws = data.frame(ex3$b) %>%
  dplyr::mutate(iter = 1:nrow(ex3$b)) %>%
  tidyr::pivot_longer(cols = c("b_1", "b_2"),
                      names_to = "component",
                      values_to = "param")

ggplot(data = b_mcmc_draws) +
  geom_line(mapping = aes(x = iter, y = param, color = component)) +
  ggtitle("Traceplot of b") +
  # ylab() +
  theme_classic()

# explore variance spikes
var_spike = sapply(X = 1:length(ex3$vars), FUN = function(x){max(unlist(ex3$vars[[x]]))})
spike_ind = which(var_spike > 100)
spike_ind = spike_ind[(spike_ind>1000)==TRUE] # neglect burn in iters
spike_info = lapply(X = 1:length(spike_ind), 
       FUN = function(x){
         list(iter = spike_ind[x], tabs = table(ex3$group_assign[spike_ind[x],]))
       })
```

### Using IG(2, b) w/ b~Ga(1,1) and empirical mean/var as prior

```{r,  message=FALSE}
# sample
set.seed(718)
n_iter = 11000
mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -1)
print(mu0)
print(Sigma0)

# ex3 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
#                         mu0 = mu0, a = 2, d = 5, f = 1, sigma_hyperprior = TRUE,
#                         k_init = 1, verbose = TRUE, print_iter = 1000)
# saveRDS(object = list(data = data, mcmc = ex3), file = paste0("./MCMC_Runs/MCMC_run_hyperprior_a2_d1_f1_n50_", Sys.Date(),".rds"))
ex3 = readRDS("./MCMC_Runs/MCMC_run_hyperprior_a2_d1_f1_n50_2023-08-03.rds")$mcmc
mean(ex3$accept[2:n_iter,])
table(ex3$k)

# traceplot for number of components k
make_k_traceplot(k = ex3$k, group_assign = ex3$group_assign)

# posterior inference before label switching fixed
mean_list_by_k3 = list_params_by_k(draws = ex3$means, burn_in = 1000, param_type = "Mean", k_vec = ex3$k)
var_list_by_k3 = list_params_by_k(draws = ex3$vars, burn_in = 1000, param_type = "Var", k_vec = ex3$k)
#sigma22 is group 2, 2nd diagonal element
prob_list_by_k3 = get_probs_by_k(probs = ex3$group_probs, 
                                n_groups = ex3$k, 
                                burn_in = 1000)
group_assign_list_by_k3 = get_assign_by_k(assign = ex3$group_assign, 
                                         n_groups = ex3$k, 
                                         burn_in = 1000)
## deal with label switching for each k

## in this case need to skip first result bc only one group was found -- can't 
## have label switching when there is only 1 group so the function fails

## this ended up not being true here after some settings were changed --- need to program
## a more robust way to do this to avoid manually changing Stephens settings and potentially
## causing erros
stephens_result3 = get_stephens_result(group_assign_list_by_k = group_assign_list_by_k3, 
                                       prob_list_by_k = prob_list_by_k3)

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$means, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3, 
                                           param_type = "Mean")
var_list_by_k_stephens3 = list_params_by_k(draws = ex3$vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

make_postsum(mcmc_df = mean_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[3]], digits = 2)

make_postsum(mcmc_df = var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[3]], digits = 2)

# empirical means & vars
# emp_mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_means, k_vec = ex3$k,
#                                            burn_in = 1000,
#                                            relabel = TRUE,
#                                            permutation = stephens_result3, 
#                                            param_type = "Mean")
emp_var_list_by_k_stephens3 = list_params_by_k(draws = ex3$emp_vars, k_vec = ex3$k,
                                           burn_in = 1000,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

# empirical vars
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = emp_var_list_by_k_stephens3[[3]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 1,
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k = 3, p = 2,
               component_no = 2,
               param_type = "Mean")

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 1,
                    p=2,
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k = 3, 
                    component_no = 2,
                    p=2,
                    param_type = "Var")

## traceplot of b parameters
b_mcmc_draws = data.frame(ex3$b) %>%
  dplyr::mutate(iter = 1:nrow(ex3$b)) %>%
  tidyr::pivot_longer(cols = c("b_1", "b_2"),
                      names_to = "component",
                      values_to = "param")

ggplot(data = b_mcmc_draws) +
  geom_line(mapping = aes(x = iter, y = param, color = component)) +
  ggtitle("Traceplot of b") +
  # ylab() +
  theme_classic()

# explore variance spikes
var_spike = sapply(X = 1:length(ex3$vars), FUN = function(x){max(unlist(ex3$vars[[x]]))})
spike_ind = which(var_spike > 100)
spike_ind = spike_ind[(spike_ind>1000)==TRUE] # neglect burn in iters
spike_info = lapply(X = 1:length(spike_ind), 
       FUN = function(x){
         list(iter = spike_ind[x], tabs = table(ex3$group_assign[spike_ind[x],]))
       })
```