---
title: "K=5 Simulation Scenario"
author: "Jonathan Klus"
date: "2024-04-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load necessary functions
source("./Multivariate_DPMM_unknownvar_DEV.R")
# source("./Multivariate_DPMM_unknownvar_DEE.R")
#source("./Multivariate_DPMM_unknownvar_UVV.R")
source("./posterior_helper_fxns.R")
source("./post_processing_inf.R")

# load R libraries
library(ggplot2)
library(gridExtra)
library(plotly)
library(label.switching)
library(LaplacesDemon)
library(parallel)
library(stringr)
library(scatterplot3d)
```

Mixture of 5 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 5. The true means are $(4, 4, -2)$, $(2, 3, 2)$, $(3, 2, 5)$, $(8, 8, 0)$, and $(9, 7, 3)$.

```{r}
################## simulate data ##############################################

set.seed(516)
nreps = 10
seeds = sample(x = 1:10^4, size = nreps, replace = FALSE)

w = rep(0.2, 5)
means = list(
  c(4, 4, -2),
  c(2, 3, 2),
  c(3, 2, 5),
  c(8, 8, 0),
  c(9, 7, 3)
)

var = diag(0.25, length(means[[1]])) #+ matrix(data = 0.1, ncol=3, nrow=3) - diag(0.1,3)

assign = sample(x = 1:length(means), size = 100, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 3, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2],
  y3 = y_matrix[,3]
)

attach(data)
scatterplot3d(x = y1, y = y2, z = y3, color = assign, angle = -45)

# ggplot(data = data, aes(x = y1, y = y2, label = rownames(data))) +
#   geom_point(color = assign) +
#   #geom_text(size = 3, hjust = 0, nudge_x = 0.5, color = assign) +
#   # geom_text(size = 3, color = assign) +
#   ggtitle("Simulated 2D Data and True Group Assignments") + 
#   theme_classic()

# yreps = lapply(X = 1:nreps, 
#            FUN = function(x){
#              set.seed(seeds[x])
#              assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
#              y = lapply(X = assign,
#                         FUN = function(x){
#                         t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
#                           })
#              return(list(y = y, assign = assign))
#            })
# 
# # make a grid of plots
# pltlist = list()
# for(rep in 1:nreps){
# 
#   y_matrix = matrix(data = unlist(yreps[[rep]]$y), ncol = 2, byrow = TRUE)
#   assign = yreps[[rep]]$assign
# 
#   data = data.frame(
#     assign = assign,
#     y1 = y_matrix[,1],
#     y2 = y_matrix[,2]
#   )
# 
#   p = ggplot(data = data, aes(x = y1, y = y2)) + #, label = rownames(data))) +
#     geom_point(color = assign, size = 0.75) +
#     #geom_text(size = 3, hjust = 0, nudge_x = 0.5, color = assign) +
#     # geom_text(size = 3, color = assign) +
#     theme_classic()
# 
#   pltlist[[rep]] = p
# }
# 
# do.call(grid.arrange, pltlist)#, top = "Simulated 2D Data and True Group Assignments")
# 
# # drop params used to generate data, except for var which is assumed known
# rm(w, means)
```
## Try fitting a model

```{r}
n_iter = 12000
x=1
sim_results_DEV = MVN_CRP_sampler_DEV(
        S = n_iter, seed = seeds[x], y = y,
        alpha = 1, r = 10, d = 1, f = 1 , g = 1, h = 10,
        sigma_hyperprior = FALSE, fix_r = FALSE,
        mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 3  ))),0), ncol = 1),
        a = 1, b = 1,
        k_init = 1, diag_weights = FALSE,
        verbose = TRUE, split_merge = FALSE #, sm_iter = 5
        )
```

