---
title: "Multivariate DPMM Simulations"
author: "Jonathan Klus"
date: "2023-05-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load necessary functions
source("./Multivariate_DPMM_knownvar.R")
source("./posterior_helper_fxns.R")

# load R libraries
library(ggplot2)
library(plotly)
library(label.switching)
library(coda)
library(tidyr)
```

## 2D Example - well separated

Mixture of 3 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 10$. The true means are $(-20,20)$, $(20,-20)$, and $(0,0)$, and
$\sum_{j}n_j = 30$.

```{r, echo=FALSE}
################## simulate data ##############################################
w = c(0.4, 0.3, 0.3)
means = list(
  c(-20, 20),
  c(20, -20),
  c(0, 0)
)

var = diag(10, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

ggplot(data = data, aes(x = y1, y = y2, label = rownames(data))) +
  #geom_point(color = assign) +
  #geom_text(size = 3, hjust = 0, nudge_x = 0.5, color = assign) +
  geom_text(size = 3, color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```
## Prior too small

```{r}
# sample
set.seed(516)
n_iter = 10^4
ex1 = MVN_CRP_sampler(S = n_iter, y = y, sigma2 = 10, alpha = 1, r = 5, 
                        mu0 = matrix(data = rep(0, 2), nrow = 2), 
                        k_init = 1, verbose = FALSE)
table(ex1$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex1$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

# posterior inference before label switching fixed
mean_list_by_k = list_means_by_k(means = ex1$means, burn_in = 100)
prob_list_by_k = get_probs_by_k(probs = ex1$group_probs, 
                                n_groups = ex1$k, 
                                burn_in = 100)
group_assign_list_by_k = get_assign_by_k(assign = ex1$group_assign, 
                                         n_groups = ex1$k, 
                                         burn_in = 100)
make_postsum(mcmc_df = mean_list_by_k[[1]])
make_postsum(mcmc_df = mean_list_by_k[[2]])
make_postsum(mcmc_df = mean_list_by_k[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")


## deal with label switching for each k 
stephens_result = lapply(X = 1:length(group_assign_list_by_k), 
                         FUN = function(x){
                           label.switching(method = "STEPHENS", 
                                           z = group_assign_list_by_k[[x]],
                                           p = prob_list_by_k[[x]])
                         }) 

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens = list_means_by_k(means = ex1$means, 
                                           burn_in = 100, 
                                           relabel = TRUE,
                                           permutation = stephens_result)
make_postsum(mcmc_df = mean_list_by_k_stephens[[1]])
make_postsum(mcmc_df = mean_list_by_k_stephens[[2]])
make_postsum(mcmc_df = mean_list_by_k_stephens[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")
```

```{r}
# sample
set.seed(516)
n_iter = 10^4
ex2 = MVN_CRP_sampler(S = n_iter, y = y, sigma2 = 10, alpha = 1, r = 30, 
                        mu0 = matrix(data = rep(0, 2), nrow = 2), 
                        k_init = 1, verbose = FALSE)
table(ex2$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex2$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

# posterior inference before label switching fixed
mean_list_by_k2 = list_means_by_k(means = ex2$means, burn_in = 100)
prob_list_by_k2 = get_probs_by_k(probs = ex2$group_probs, 
                                n_groups = ex2$k, 
                                burn_in = 100)
group_assign_list_by_k2 = get_assign_by_k(assign = ex2$group_assign, 
                                         n_groups = ex2$k, 
                                         burn_in = 100)
make_postsum(mcmc_df = mean_list_by_k2[[1]])
make_postsum(mcmc_df = mean_list_by_k2[[2]])
make_postsum(mcmc_df = mean_list_by_k2[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k2, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k2, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k2, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k2, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")


## deal with label switching for each k 
stephens_result2 = lapply(X = 1:length(group_assign_list_by_k2), 
                         FUN = function(x){
                           label.switching(method = "STEPHENS", 
                                           z = group_assign_list_by_k2[[x]],
                                           p = prob_list_by_k2[[x]])
                         }) 

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens2 = list_means_by_k(means = ex2$means, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result2)
make_postsum(mcmc_df = mean_list_by_k_stephens2[[1]])
make_postsum(mcmc_df = mean_list_by_k_stephens2[[2]])
make_postsum(mcmc_df = mean_list_by_k_stephens2[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens2, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens2, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens2, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens2, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")

```


## 2D Example - close together

Mixture of 3 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 10$. The true means are $(10,10)$, $(5,0)$, and $(0,10)$, and
$\sum_{j}n_j = 30$.

```{r, echo=FALSE}
################## simulate data ##############################################
set.seed(718)
w = c(1/3, 1/3, 1/3)
means = list(
  c(10, 10),
  c(5, 0),
  c(0, 10)
)

var = diag(9, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

ggplot(data = data, aes(x = y1, y = y2)) +
  geom_point(color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```

```{r}
# sample
set.seed(516)
n_iter = 10^4
ex3 = MVN_CRP_sampler(S = n_iter, y = y, sigma2 = 9, alpha = 1, r = 30, 
                        mu0 = round(Reduce(f = "+", x = y)/length(y),0),
                      # center prior at observed data mean
                        k_init = 1, verbose = FALSE)
table(ex3$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex3$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

# posterior inference before label switching fixed
mean_list_by_k3 = list_means_by_k(means = ex3$means, burn_in = 100)
prob_list_by_k3 = get_probs_by_k(probs = ex3$group_probs, 
                                n_groups = ex3$k, 
                                burn_in = 100)
group_assign_list_by_k3 = get_assign_by_k(assign = ex3$group_assign, 
                                         n_groups = ex3$k, 
                                         burn_in = 100)
make_postsum(mcmc_df = mean_list_by_k3[[1]])
make_postsum(mcmc_df = mean_list_by_k3[[2]])
make_postsum(mcmc_df = mean_list_by_k3[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k3, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k3, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k3, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k3, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")


## deal with label switching for each k 
stephens_result3 = lapply(X = 1:length(group_assign_list_by_k3), 
                         FUN = function(x){
                           label.switching(method = "STEPHENS", 
                                           z = group_assign_list_by_k3[[x]],
                                           p = prob_list_by_k3[[x]])
                         }) 

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens3 = list_means_by_k(means = ex3$means, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result3)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[1]])
make_postsum(mcmc_df = mean_list_by_k_stephens3[[2]])
make_postsum(mcmc_df = mean_list_by_k_stephens3[[3]])
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 1, 
                    component_no = 1,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 1, 
                    component_no = 2,
                    title_note = "K=3")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 2, 
                    component_no = 1,
                    title_note = "K=4")
make_mean_traceplot(mean_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 2, 
                    component_no = 2,
                    title_note = "K=4")

```