---
title: "Multivariate DPMM Unknown Var Simulations"
author: "Jonathan Klus"
date: "2023-07-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load necessary functions
source("./Multivariate_DPMM_unknownvar.R")
source("./posterior_helper_fxns.R")

# load R libraries
library(ggplot2)
library(plotly)
library(label.switching)
library(coda)
library(tidyr)
```

## 2D Example - well separated

Mixture of 3 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 10$. The true means are $(-20,20)$, $(20,-20)$, and $(0,0)$, and
$\sum_{j}n_j = 30$.

```{r, echo=FALSE}
################## simulate data ##############################################
w = c(0.4, 0.3, 0.3)
means = list(
  c(-20, 20),
  c(20, -20),
  c(0, 0)
)

var = diag(10, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

# empirical means and variances
data %>%
  group_by(assign) %>%
  dplyr::summarize(mean(y1), mean(y2), var(y1), var(y2))

ggplot(data = data, aes(x = y1, y = y2, label = rownames(data))) +
  #geom_point(color = assign) +
  #geom_text(size = 3, hjust = 0, nudge_x = 0.5, color = assign) +
  geom_text(size = 3, color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```
```{r}
# sample
set.seed(516)
n_iter = 10^4

mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -2)

ex1 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
                        mu0 = mu0, a = 1, b = 2,
                        k_init = 1, verbose = TRUE, print_iter = 100)
# saveRDS(object = ex1, file = "./Data/ex1_results.rds")

mean(ex1$accept[2:n_iter,])
table(ex1$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex1$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

group_assign_list_by_k = get_assign_by_k(assign = ex1$group_assign, 
                                         n_groups = ex1$k, 
                                         burn_in = 100)

prob_list_by_k = get_probs_by_k(probs = ex1$group_probs, 
                                n_groups = ex1$k, 
                                burn_in = 100)

# ## deal with label switching for each k 
stephens_result = lapply(X = 1:length(group_assign_list_by_k),
                         FUN = function(x){
                           label.switching(method = "STEPHENS",
                                           z = group_assign_list_by_k[[x]],
                                           p = prob_list_by_k[[x]])
                         })

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens = list_means_by_k(means = ex1$means,
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result)
var_list_by_k_stephens = list_params_by_k(draws = ex1$vars,
                                           burn_in = 100,
                                           relabel = TRUE,
                                          param_type = "Var",
                                          permutation = stephens_result)

make_postsum(mcmc_df = mean_list_by_k_stephens[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens[[3]], digits = 2)

make_postsum(mcmc_df = var_list_by_k_stephens[[2]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens[[3]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens,
               k_index = 2,
               component_no = 1,
               param_type = "Mean",
               title_note = "K=3")
make_traceplot(param_list_by_k = mean_list_by_k_stephens,
               k_index = 2,
               component_no = 2,
               param_type = "Mean",
               title_note = "K=3")
make_traceplot(param_list_by_k = mean_list_by_k_stephens,
               k_index = 3,
               component_no = 1,
               param_type = "Mean",
               title_note = "K=4")
make_traceplot(param_list_by_k = mean_list_by_k_stephens,
               k_index = 3,
               component_no = 2,
               param_type = "Mean",
               title_note = "K=4")

make_traceplot(param_list_by_k = var_list_by_k_stephens,
               k_index = 2,
               component_no = 1,
               param_type = "Var",
               title_note = "K=3")
make_traceplot(param_list_by_k = var_list_by_k_stephens,
               k_index = 2,
               component_no = 2,
               param_type = "Var",
               title_note = "K=3")

make_traceplot(param_list_by_k = var_list_by_k_stephens,
               k_index = 3,
               component_no = 1,
               param_type = "Var",
               title_note = "K=4")
make_traceplot(param_list_by_k = var_list_by_k_stephens,
               k_index = 3,
               component_no = 2,
               param_type = "Var",
               title_note = "K=4")
```

## 2D Example - close together

Mixture of 3 multivariate normal densities all with diagonal variance structure
and $\sigma^2 = 10$. The true means are $(10,10)$, $(5,0)$, and $(0,10)$, and
$\sum_{j}n_j = 30$.

```{r, echo=FALSE}
################## simulate data ##############################################
set.seed(516)
w = c(1/3, 1/3, 1/3)
means = list(
  c(10, 10),
  c(5, 0),
  c(0, 10)
)

var = diag(9, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

# empirical means and variances
data %>%
  group_by(assign) %>%
  dplyr::summarize(mean(y1), mean(y2), var(y1), var(y2))

ggplot(data = data, aes(x = y1, y = y2)) +
  geom_point(color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```

```{r}
# sample
set.seed(516)
n_iter = 10^4
mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -1)

ex3 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
                        mu0 = mu0, a = 1, b = 1,
                        k_init = 1, verbose = TRUE, print_iter = 100)
# saveRDS(object = ex3, file = "./Data/ex3_results.rds")

mean(ex3$accept[2:n_iter,])
table(ex3$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex3$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

## deal with label switching for each k
group_assign_list_by_k3 = get_assign_by_k(assign = ex3$group_assign, 
                                         n_groups = ex3$k, 
                                         burn_in = 100)

prob_list_by_k3 = get_probs_by_k(probs = ex3$group_probs, 
                                n_groups = ex3$k, 
                                burn_in = 100)

## in this case need to skip first result bc only one group was found -- can't 
## have label switching when there is only 1 group so the function fails
stephens_result3 = lapply(X = 2:length(group_assign_list_by_k3), 
                         FUN = function(x){
                           label.switching(method = "STEPHENS", 
                                           z = group_assign_list_by_k3[[x]],
                                           p = prob_list_by_k3[[x]])
                         }) 

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens3 = list_params_by_k(draws = ex3$means, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result3, 
                                           param_type = "Mean")
var_list_by_k_stephens3 = list_params_by_k(draws = ex3$vars, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result3,
                                           param_type = "Var")

make_postsum(mcmc_df = mean_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens3[[3]], digits = 2)

make_postsum(mcmc_df = var_list_by_k_stephens3[[1]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[2]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens3[[3]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k_index = 2, 
               component_no = 1,
               title_note = "K=2",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k_index = 2, 
               component_no = 2,
               title_note = "K=2",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k_index = 3, 
               component_no = 1,
               title_note = "K=3",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
               k_index = 3, 
               component_no = 2,
               title_note = "K=3",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 4, 
                    component_no = 1,
                    title_note = "K=4",
                    param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens3, 
                    k_index = 4, 
                    component_no = 2,
                    title_note = "K=4",
                    param_type = "Mean")

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k_index = 3, 
                    component_no = 1,
                    title_note = "K=3",
                    param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k_index = 3, 
                    component_no = 2,
                    title_note = "K=3",
                    param_type = "Var")

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k_index = 3, 
                    component_no = 1,
                    title_note = "K=3",
                    param_type = "Var", 
                    log_scale = TRUE)

make_traceplot(param_list_by_k = var_list_by_k_stephens3, 
                    k_index = 3, 
                    component_no = 2,
                    title_note = "K=3",
                    param_type = "Var", 
                    log_scale = TRUE)

# searching for variance spikes
var_spike = sapply(X = 1:length(ex3$vars), FUN = function(x){max(unlist(ex3$vars[[x]]))})
spike_ind = which(var_spike > 1000)
ex3$k[spike_ind]

# example
ex3$means[[spike_ind[72]]]
ex3$vars[[spike_ind[72]]]
ex3$group_assign[spike_ind[72],]

ex3$means[[spike_ind[73]]]
ex3$vars[[spike_ind[73]]]
ex3$group_assign[spike_ind[73],]

ex3$means[[spike_ind[74]]]
ex3$vars[[spike_ind[74]]]
ex3$group_assign[spike_ind[74],]

ex3$means[[spike_ind[75]]]
ex3$vars[[spike_ind[75]]]
ex3$group_assign[spike_ind[75],]


```

## Only 1 true group

$\mu = (5,5), \Sigma = 10*I_2$

```{r, echo=FALSE}
################## simulate data ##############################################
set.seed(718)
w = c(1)
means = list(
  c(5,5)
)

var = diag(10, length(means[[1]])) # variances known, diagonal, and equal

assign = sample(x = 1:length(means), size = 30, replace = TRUE, prob = w)
y = lapply(X = assign,
           FUN = function(x){
             t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
           })
y_matrix = matrix(data = unlist(y), ncol = 2, byrow = TRUE)

data = data.frame(
  assign = assign,
  y1 = y_matrix[,1],
  y2 = y_matrix[,2]
)

# empirical means and variances
data %>%
  group_by(assign) %>%
  dplyr::summarize(mean(y1), mean(y2), var(y1), var(y2))

ggplot(data = data, aes(x = y1, y = y2, label = rownames(data))) +
  #geom_point(color = assign) +
  #geom_text(size = 3, hjust = 0, nudge_x = 0.5, color = assign) +
  geom_text(size = 3, color = assign) +
  ggtitle("Simulated 2D Data and True Group Assignments") + 
  theme_classic()

# drop params used to generate data, except for var which is assumed known
rm(w, means)
```

```{r}
# sample
set.seed(516)
n_iter = 10^4
mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1)
Sigma0 = round(cov(matrix(unlist(y), ncol = 2)), -1)

ex4 = MVN_CRP_sampler(S = n_iter, y = y, alpha = 1, Sigma0 = Sigma0,
                        mu0 = mu0, a = 1, b = 1,
                        k_init = 1, verbose = TRUE, print_iter = 1000)

mean(ex4$accept[2:n_iter,])
table(ex4$k)

# traceplot for number of components k
ggplot(mapping = aes(x = 1:n_iter, y = ex4$k)) + 
  geom_line() +
  ggtitle("Traceplot of no. components K") +
  xlab("iter") + 
  ylab("K") + 
  theme_classic()

# posterior inference before label switching fixed
mean_list_by_k4 = list_means_by_k(means = ex4$means, burn_in = 100)
prob_list_by_k4 = get_probs_by_k(probs = ex4$group_probs, 
                                n_groups = ex4$k, 
                                burn_in = 100)
group_assign_list_by_k4 = get_assign_by_k(assign = ex4$group_assign, 
                                         n_groups = ex4$k, 
                                         burn_in = 100)

make_postsum(mcmc_df = mean_list_by_k4[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k4[[2]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k4[[3]], digits = 2)
## deal with label switching for each k

## in this case need to skip first result bc only one group was found -- can't 
## have label switching when there is only 1 group so the function fails
stephens_result4 = lapply(X = 2:length(group_assign_list_by_k4), 
                         FUN = function(x){
                           label.switching(method = "STEPHENS", 
                                           z = group_assign_list_by_k4[[x]],
                                           p = prob_list_by_k4[[x]])
                         }) 

## now reorder means to deal with label switching and redo posterior inference and 
## traceplots
mean_list_by_k_stephens4 = list_means_by_k(means = ex4$means, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           permutation = stephens_result4)

var_list_by_k_stephens4 = list_params_by_k(draws = ex4$vars, 
                                           burn_in = 100,
                                           relabel = TRUE,
                                           param_type = "Var",
                                           permutation = stephens_result4)

make_postsum(mcmc_df = mean_list_by_k_stephens4[[1]], digits = 2)
make_postsum(mcmc_df = mean_list_by_k_stephens4[[2]], digits = 2)

make_postsum(mcmc_df = var_list_by_k_stephens4[[1]], digits = 2)
make_postsum(mcmc_df = var_list_by_k_stephens4[[2]], digits = 2)

make_traceplot(param_list_by_k = mean_list_by_k_stephens4, 
               k_index = 1, 
               component_no = 1,
               title_note = "K=1",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens4, 
               k_index = 1, 
               component_no = 2,
               title_note = "K=1",
               param_type = "Mean")

make_traceplot(param_list_by_k = mean_list_by_k_stephens4, 
               k_index = 2, 
               component_no = 1,
               title_note = "K=2",
               param_type = "Mean")
make_traceplot(param_list_by_k = mean_list_by_k_stephens4, 
               k_index = 2, 
               component_no = 2,
               title_note = "K=2",
               param_type = "Mean")

make_traceplot(param_list_by_k = var_list_by_k_stephens4, 
               k_index = 1, 
               component_no = 1,
               title_note = "K=1",
               param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens4, 
               k_index = 1, 
               component_no = 2,
               title_note = "K=1",
               param_type = "Var")

make_traceplot(param_list_by_k = var_list_by_k_stephens4, 
               k_index = 2, 
               component_no = 1,
               title_note = "K=2",
               param_type = "Var")
make_traceplot(param_list_by_k = var_list_by_k_stephens4, 
               k_index = 2, 
               component_no = 2,
               title_note = "K=2",
               param_type = "Var")
```
