---
title: "Sim Study Results Investigation"
author: "Jonathan Klus"
date: "2024-09-27"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# homemade functions
# source("./Multivariate_DPMM_unknownvar_DEV.R")
# source("./Multivariate_DPMM_unknownvar_DEE.R")
#source("./Multivariate_DPMM_unknownvar_UVV.R")
source("./posterior_helper_fxns.R")
source("./post_processing_inf.R")

# load R libraries
library(ggplot2)
library(dplyr)
library(stringr)
library(scatterplot3d)
library(genMCMCDiag)

######################## DEFINE HELPER FUNCTIONS################################
# running locally
# data_path = "//GENE.bst.rochester.edu/Projects/JKSTproj/BlueHive_Sim_Results/"

# running on server
data_path = "/projects/jklus/JKSTproj/BlueHive_Sim_Results/SummaryProposal"
```

### with SM

```{r}
# n=30
sim_dir = "MODSUM_conjDEE_3close_n30_withSM_sim_results_2024_07_28"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(result_wd)
for(i in 1:10){
  output = readRDS(paste0(result_wd, "/", result_file[i]))
  # output$settings
  # dim(output$group_assign)
  iter_k = sapply(X = 1:nrow(output$group_assign), 
                  FUN = function(x){
                    length(unique(output$group_assign[x,]))
                  })
  plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
       main = paste0("Traceplot of K, ", "Dataset ", i))
}

```

```{r}
# n=100
sim_dir = "MODSUM_conjDEE_3close_n100_withSM_sim_results_2024_07_28"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(result_wd)
for(i in 1:length(result_file)){
  output = readRDS(paste0(result_wd, "/", result_file[i]))
  # output$settings
  # dim(output$group_assign)
  # iter_k = sapply(X = 1:nrow(output$group_assign), 
  #                 FUN = function(x){
  #                   length(unique(output$group_assign[x,]))
  #                 })
  # plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
  #        main = paste0("Traceplot of K, ", "Dataset ", i))
  
  # do Luke diagnostics
  adj_matrix = get_adjmat_groupassign(group_assign = output$group_assign)
  genMCMCDiag::genDiagnostic(mhDraws = adj_matrix,
                             diagnostics = "gelmanRubin",
                             method = "lanfear", 
                             distance = hammingDist)
}

```

```{r}
# n=300
sim_dir = "MODSUM_conjDEE_3close_n300_withSM_sim_results_2024_07_14"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(result_wd)

for(i in 1:10){
  
  output = readRDS(paste0(result_wd, "/", result_file[i]))
  output$settings
  dim(output$group_assign)
  iter_k = sapply(X = 1:nrow(output$group_assign), 
                  FUN = function(x){
                    length(unique(output$group_assign[x,]))
                  })
  plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
         main = paste0("Traceplot of K, ", "Dataset ", i))
  
}

```




```{r, include=FALSE, eval=FALSE}
### without SM
# n=30
sim_dir = "MODSUM_conjDEE_3close_n30_noSM_sim_results_2024_07_11"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(file_ext)
output = readRDS(paste0(result_wd, "/", result_file[10]))
output$settings
dim(output$group_assign)
iter_k = sapply(X = 1:nrow(output$group_assign), 
                FUN = function(x){
                  length(unique(output$group_assign[x,]))
                })
plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
       main = paste0("Traceplot of K, ", "Dataset ", i))
```

```{r, include=FALSE, eval=FALSE}
# n=100
sim_dir = "MODSUM_conjDEE_3close_n100_noSM_sim_results_2024_07_11"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(file_ext)
output = readRDS(paste0(result_wd, "/", result_file[9]))
output$settings
dim(output$group_assign)
iter_k = sapply(X = 1:nrow(output$group_assign), 
                FUN = function(x){
                  length(unique(output$group_assign[x,]))
                })
plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
       main = paste0("Traceplot of K, ", "Dataset ", i))
```

```{r, include=FALSE, eval=FALSE}
# n=300
sim_dir = "MODSUM_conjDEE_3close_n300_noSM_sim_results_2024_07_11"  # found MAP(K)=16, truth is 3
result_wd = paste0(data_path, "/", sim_dir)
result_file = list.files(file_ext)
output = readRDS(paste0(result_wd, "/", result_file[4]))
output$settings
dim(output$group_assign)
iter_k = sapply(X = 1:nrow(output$group_assign), 
                FUN = function(x){
                  length(unique(output$group_assign[x,]))
                })
plot(x = 1:length(iter_k), y = iter_k, type = "l", xlab = "iter", ylab = "K",
       main = paste0("Traceplot of K, ", "Dataset ", i))
```
