---
title: "UVV Example"
author: "Jonathan Klus"
date: "2025-06-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# load necessary functions
# source("./Samplers/Multivariate_DPMM_unknownvar_DEE.R")
# source("./Samplers/Multivariate_DPMM_unknownvar_DEV.R")
# source("./Samplers/Multivariate_DPMM_nonconj_UVV.R")
# source("./Samplers/Multivariate_DPMM_nonconj_DVV.R")
# source("./Samplers/Multivariate_DPMM_nonconj_DEV.R")
# source("./Samplers/Multivariate_DPMM_unknownvar_UVV.R")
source("./Samplers/posterior_helper_fxns.R")
source("./Samplers/post_processing_inf.R")

# load R libraries
library(ggplot2)
library(mclust)
library(LaplacesDemon)
library(mvtnorm)
library(stringr)
library(gridExtra)
library(dplyr)
library(knitr) # kable
# library(kableExtra) # use for complex tables http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
library(xtable)
```

```{r}
# Well separated simulation setting 

################## simulate data ##############################################

# set.seed(516)
x = 1 # dataset100
seeds = readRDS("./SimStudy/BHsimseeds.rds")
set.seed(seeds[x])

# 
w = rep(1/3,3)
# 
# # negative corr
# means = list(
#    c(-20, 20),
#    c(20, -20),
#    c(0, 0)
#  )

# positive corr
means = list(
    c(-20, -20),
    c(20, 20),
    c(0, 0)
  )

# 5 group 3d

  # w = rep(0.2, 5)
  # 
  # means = list(
  #   c(4, 4, -2),
  #   c(2, 3, 2),
  #   c(3, 2, 5),
  #   c(8, 8, 0),
  #   c(9, 7, 3)
  # )
  # 
  # var = diag(0.25, length(means[[1]]))


  var = diag(10, length(means[[1]])) # variances known, diagonal, and equal


set.seed(seeds[x])
assign = sample(x = 1:length(means), size = 100, replace = TRUE, prob = w)
y = lapply(X = assign,
          FUN = function(x){
          t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
            })


# drop params used to generate data, except for var which is assumed known
mu_true = means
var_true = var
# yreps # 2nd element is assign
rm(w, means)
```


## UVV 

```{r, include=FALSE, eval=FALSE}
source("./Samplers/Multivariate_DPMM_unknownvar_UVV.R")

n_iter = 5000

sim_results_UVV = MVN_CRP_sampler_UVV(
        S = n_iter, seed = seeds[x], y = y,
        alpha = 1, r = 1, g = 1, h = 25, nu = 3, fix_r = FALSE,
        mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 2))),0), ncol = 1),
        lambda0 = diag(100,2),
        k_init = 1, init_method = "kmeans", diag_weights = FALSE, 
        verbose = TRUE, split_merge = FALSE, print_iter = 1, print_start = 0
        )

mod_sum_UVV = dpmm_summary(output = sim_results_DEV, 
       print_k_sum = TRUE, 
       print_phi_sum = TRUE,
       make_traceplot = FALSE,
       burn_in = 0, t_hold = 0, 
       num_dims = 2, equal_var = TRUE,
       calc_perf = FALSE, mu_true = mu_true, 
       var_true = var_true, assign_true = assign)

plot(mod_sum$var_list_by_k_stephens[[1]]$sigma_1_1, type = "l", 
     xlab = "iter", ylab = "sigma2")
```

## Non-conjugate UVV

```{r, include=FALSE, eval=FALSE}

source("./Samplers/Multivariate_DPMM_nonconj_UVV.R")

n_iter = 5000

sim_results_nonconjUVV = MVN_CRP_nonconj_UVV(
        S = n_iter, seed = seeds[x], y = y, 
        alpha = 1, Sigma0 = diag(100,3), 
        mu0 = matrix(round((colMeans(matrix(unlist(y), ncol = 3))),0), ncol = 1),
        k_init = 1, init_method = "kmeans",
        nu = 5, Lambda0 = diag(1,3),
        standardize_y = FALSE,
        verbose = TRUE, split_merge = TRUE, sm_iter = 5, sm_freq = 10, 
        diag_weights = FALSE, verbose = TRUE, print_iter = 10, print_start = 0)


mod_sum_nonconjUVV = dpmm_summary(output = sim_results_nonconjUVV, 
       print_k_sum = TRUE, 
       print_phi_sum = TRUE,
       make_traceplot = FALSE,
       burn_in = 500, t_hold = 100, 
       num_dims = 3, equal_var = FALSE, off_diag = TRUE,
       calc_perf = TRUE, mu_true = mu_true, 
       var_true = lapply(X = 1:length(mu_true), FUN = function(x){var_true}), 
       assign_true = assign)

```