---
title: "Sampler Test Script"
author: "Jonathan Klus"
date: "2024-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

source("./Samplers/posterior_helper_fxns.R")
source("./Samplers/post_processing_inf.R")

# load R libraries
library(ggplot2)
library(mclust)
library(LaplacesDemon)
library(mvtnorm)
library(stringr)
library(gridExtra)
library(dplyr)
library(knitr) # kable
# library(kableExtra) # use for complex tables http://haozhu233.github.io/kableExtra/awesome_table_in_pdf.pdf
library(xtable)
```

```{r}
get_empcov <- function(seed, scenario, n){
  
  set.seed(seed)
  
  # simulate data
  if(scenario == "wellsep"){
    
      w = rep(1/3,3)

      # positive corr
      means = list(
          c(-20, -20),
          c(20, 20),
          c(0, 0)
        )
    
      var = diag(10, length(means[[1]])) # variances known, diagonal, and equal
    
  } else if(scenario == "close"){
    
      w = c(.35, .25, .4)
  
      means = list(
        #c(10, 10),
        c(-1, -5),
        c(0, 10),
        c(10,2)
      )
  
      var = diag(4, length(means[[1]])) # variances known, diagonal, and equal

    
  } else if(scenario == "5grp3d"){
    
      w = rep(0.2, 5)

      means = list(
          c(4, 4, -2),
          c(2, 3, 2),
          c(3, 2, 5),
          c(8, 8, 0),
          c(9, 7, 3)
          )

      var = diag(0.25, length(means[[1]]))
    
  }
  
  assign = sample(x = 1:length(means), size = n, replace = TRUE, prob = w)
  y = t(sapply(X = assign,
            FUN = function(x){
            t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
              }))
  
  # calculate empirical covariance of each group
    cov_matrix = lapply(X = unique(assign), 
                   FUN = function(x){
                     cov(y[assign == x,])
                   })
    
  return(cov_matrix)

}


summarize_cov <- function(seeds, n, scenario){
  
  if(scenario %in% c("close", "wellsep")){
    
        cov_accum = list(matrix(data = 0, ncol = 2, nrow = 2),
                         matrix(data = 0, ncol = 2, nrow = 2),
                         matrix(data = 0, ncol = 2, nrow = 2))
    off_diag_elements = list(vector(mode = "numeric", length = length(seeds)),
                         vector(mode = "numeric", length = length(seeds)),
                         vector(mode = "numeric", length = length(seeds)))
   diag_diff = list(vector(mode = "numeric", length = length(seeds)),
                     vector(mode = "numeric", length = length(seeds)),
                     vector(mode = "numeric", length = length(seeds)))
    for(x in 1:length(seeds)){
       cov_i = get_empcov(seed = seeds[x], scenario = scenario, n = n)
       if(length(cov_i) == 3){
          cov_accum[[1]] = cov_accum[[1]] + cov_i[[1]]
          cov_accum[[2]] = cov_accum[[2]] + cov_i[[2]]
          cov_accum[[3]] = cov_accum[[3]] + cov_i[[3]]
          off_diag_elements[[1]][x] = cov_i[[1]][1,2]
          off_diag_elements[[2]][x] = cov_i[[2]][1,2]
          off_diag_elements[[3]][x] = cov_i[[3]][1,2]
          diag_diff[[1]][x] = abs(cov_i[[1]][1,1] - cov_i[[1]][2,2])
          diag_diff[[2]][x] = abs(cov_i[[2]][1,1] - cov_i[[2]][2,2])
          diag_diff[[3]][x] = abs(cov_i[[3]][1,1] - cov_i[[3]][2,2])
       } else{
         cat(paste0("\n For seed #", x, " true num groups simulated = ", length(cov_i)))
       }

    }
    
    all_off_diag = c(off_diag_elements[[1]],off_diag_elements[[2]],off_diag_elements[[3]])
    cat("\n n=", n, ", scenario=", scenario)
        cat("\n All-component off_diag med=", median(all_off_diag), 
            " , iqr=", IQR(all_off_diag), "\n")
        
    all_diag_diff = c(diag_diff[[1]],diag_diff[[2]],diag_diff[[3]])
    cat("\n n=", n, ", scenario=", scenario)
        cat("\n All-component diag_diff med=", median(all_diag_diff), 
            " , iqr=", IQR(all_diag_diff), "\n")  
    # cat("\n Component 1 off_diag med=", median(off_diag_elements[[1]]), " , iqr=", IQR(off_diag_elements[[1]]))
    # cat("\n Component 1 off_diag med=", median(off_diag_elements[[2]]), " , iqr=", IQR(off_diag_elements[[2]]))
    # cat("\n Component 1 off_diag med=", median(off_diag_elements[[3]]), " , iqr=", IQR(off_diag_elements[[3]]), "\n")
    
    return(list(avg_cov1 = cov_accum[[1]]/length(seeds),
          avg_cov2 = cov_accum[[2]]/length(seeds),
          avg_cov3 = cov_accum[[3]]/length(seeds)))
    
  } else if(scenario == "5grp3d"){
    
      cov_accum = list(matrix(data = 0, ncol = 3, nrow = 3),
                       matrix(data = 0, ncol = 3, nrow = 3),
                       matrix(data = 0, ncol = 3, nrow = 3),
                       matrix(data = 0, ncol = 3, nrow = 3),
                       matrix(data = 0, ncol = 3, nrow = 3))
      off_diag_elements = list(vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)),
                           vector(mode = "numeric", length = length(seeds)))
      for(x in 1:length(seeds)){
         cov_i = get_empcov(seed = seeds[x], scenario = scenario, n = n)
         if(length(cov_i) == 5){
           
           cov_accum[[1]] = cov_accum[[1]] + cov_i[[1]]
           cov_accum[[2]] = cov_accum[[2]] + cov_i[[2]]
           cov_accum[[3]] = cov_accum[[3]] + cov_i[[3]]
           cov_accum[[4]] = cov_accum[[4]] + cov_i[[4]]
           cov_accum[[5]] = cov_accum[[5]] + cov_i[[5]]
           
           off_diag_elements[[1]][x] = cov_i[[1]][1,2]
           off_diag_elements[[2]][x] = cov_i[[2]][1,2]
           off_diag_elements[[3]][x] = cov_i[[3]][1,2]
           off_diag_elements[[4]][x] = cov_i[[4]][1,2]
           off_diag_elements[[5]][x] = cov_i[[5]][1,2]
           
           off_diag_elements[[6]][x] = cov_i[[1]][1,3]
           off_diag_elements[[7]][x] = cov_i[[2]][1,3]
           off_diag_elements[[8]][x] = cov_i[[3]][1,3]
           off_diag_elements[[9]][x] = cov_i[[4]][1,3]
           off_diag_elements[[10]][x] = cov_i[[5]][1,3]
           
           off_diag_elements[[11]][x] = cov_i[[1]][2,3]
           off_diag_elements[[12]][x] = cov_i[[2]][2,3]
           off_diag_elements[[13]][x] = cov_i[[3]][2,3]
           off_diag_elements[[14]][x] = cov_i[[4]][2,3]
           off_diag_elements[[15]][x] = cov_i[[5]][2,3]
           
         } else{
           cat(paste0("\n For seed #", x, " true num groups simulated = ", length(cov_i)))
         }

      }
      
      print(summary(off_diag_elements[[1]]))
      print(summary(off_diag_elements[[2]]))
      print(summary(off_diag_elements[[3]]))
      print(summary(off_diag_elements[[4]]))
      print(summary(off_diag_elements[[5]]))
      print(summary(off_diag_elements[[6]]))
      print(summary(off_diag_elements[[7]]))
      print(summary(off_diag_elements[[8]]))
      print(summary(off_diag_elements[[9]]))
      print(summary(off_diag_elements[[10]]))
      print(summary(off_diag_elements[[11]]))
      print(summary(off_diag_elements[[12]]))
      print(summary(off_diag_elements[[13]]))
      print(summary(off_diag_elements[[14]]))
      print(summary(off_diag_elements[[15]]))
      
      return(list(avg_cov1 = cov_accum[[1]]/length(seeds),
            avg_cov2 = cov_accum[[2]]/length(seeds),
            avg_cov3 = cov_accum[[3]]/length(seeds),
            avg_cov3 = cov_accum[[4]]/length(seeds),
            avg_cov3 = cov_accum[[5]]/length(seeds)))
  }
  

}



```

## Well-separated

```{r}
seeds = readRDS("./BHsimseeds.rds")

well_sep30 = summarize_cov(seeds = seeds, n = 30, scenario = "wellsep")
well_sep100 = summarize_cov(seeds = seeds, n = 100, scenario = "wellsep")
well_sep300 = summarize_cov(seeds = seeds, n = 300, scenario = "wellsep")
```
## Close

```{r}
close_30 = summarize_cov(seeds = seeds, n = 30, scenario = "close")
close_100 = summarize_cov(seeds = seeds, n = 100, scenario = "close")
close_300 = summarize_cov(seeds = seeds, n = 300, scenario = "close")
```

## 5-group

```{r}
summarize_cov(seeds = seeds, n = 30, scenario = "5grp3d")
summarize_cov(seeds = seeds, n = 100, scenario = "5grp3d")
summarize_cov(seeds = seeds, n = 300, scenario = "5grp3d")
```
