---
title: "Multichain Comp - Luke D Paper"
author: "Jonathan Klus"
date: "2024-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set

# load necessary functions
source("./Multivariate_DPMM_unknownvar_DEV.R")
source("./posterior_helper_fxns.R")
# source("./post_processing_inf.R")

# load R libraries
library(ggplot2)
library(gridExtra)
library(plotly)
library(label.switching)
library(LaplacesDemon)
library(parallel)
library(stringr)
library(genMCMCDiag)
```

## Generate Data - Well Separated

```{r}
################## simulate data ##############################################

set.seed(516)
nreps = 10
seeds = sample(x = 1:10^4, size = nreps, replace = FALSE)

w = c(0.4, 0.3, 0.3)
means = list(
  c(-20, 20),
  c(20, -20),
  c(0, 0)
)

var = diag(10, length(means[[1]])) # variances known, diagonal, and equal

yreps = lapply(X = 1:nreps, 
           FUN = function(x){
             set.seed(seeds[x])
             assign = sample(x = 1:length(means), size = 100, replace = TRUE, prob = w)
             y = lapply(X = assign,
                        FUN = function(x){
                        t(mvtnorm::rmvnorm(n = 1, mean = means[[x]], sigma = var))
                          })
             return(list(y = y, assign = assign))
           })
```

## Fit Model


```{r}
n_iter = 12000
n_chains = 5
use_cores = min(parallel::detectCores(), n_chains)

# trying to fit with potential bad priors --- make variances too small
multichain_sim_results_1 = parallel::mclapply(X = 1:n_chains, mc.cores = use_cores,
      FUN = function(x){MVN_CRP_sampler_DEV(
        S = n_iter, seed = seeds[x], y = yreps[[1]]$y,
          alpha = 1, r = 1, g = 1, h = 1,
          sigma_hyperprior = FALSE, fix_r = FALSE,
          mu0 = matrix(round((colMeans(matrix(unlist(yreps[[1]]$y), ncol = 2))),0), ncol = 1),
          a = 1, b = 1,
          k_init = x, diag_weights = TRUE,
          verbose = FALSE, split_merge = FALSE
        )}
      )

# save results
datafile_name = paste0("../MCMC_Runs/conjDEVsamp_5chain_wellsep_noSM_LukeD_",
                       stringr::str_replace_all(Sys.Date(), pattern = "-", replacement = "_"), ".rds")
saveRDS(object = multichain_sim_results_1, file = datafile_name)
```

## Run Luke's Diagnostics

```{r}

# including burn-in

mcmc_list1 = lapply(X = 1:length(multichain_sim_results_1), 
                   FUN = function(x){
                     multichain_sim_results_1[[x]]$pairwise_mats$adj_by_iter
                   })

# make traceplots & get diagnostics
genDiagnostic(mhDraws = mcmc_list1, 
              method = "lanfear", 
              distance = hammingDist)

# excluding burn-in
burn_in = 2000
mcmc_list2 = lapply(X = 1:length(multichain_sim_results_1), 
                   FUN = function(x){
                     multichain_sim_results_1[[x]]$pairwise_mats$adj_by_iter[(burn_in+1):n_iter]
                   })

# make traceplots & get diagnostics
genDiagnostic(mhDraws = mcmc_list2, 
              method = "lanfear", 
              distance = hammingDist)

```

